# Generated by Django 4.2.7 on 2026-01-09 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("masters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consignor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("gstin", models.CharField(max_length=15, unique=True)),
                ("pan", models.CharField(blank=True, max_length=10)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "state_code",
                    models.CharField(
                        blank=True, help_text="GST State Code", max_length=2
                    ),
                ),
                ("pincode", models.CharField(max_length=10)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                (
                    "transporter_code",
                    models.CharField(
                        blank=True, help_text="Vendor/Transporter Code", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Consignor",
                "verbose_name_plural": "Consignors",
                "db_table": "consignors",
            },
        ),
        migrations.AlterModelOptions(
            name="party",
            options={
                "verbose_name": "Party/Consignee",
                "verbose_name_plural": "Parties/Consignees",
            },
        ),
        migrations.RemoveField(
            model_name="party",
            name="credit_days",
        ),
        migrations.RemoveField(
            model_name="party",
            name="credit_limit",
        ),
        migrations.RemoveField(
            model_name="truck",
            name="pan_number",
        ),
        migrations.AddField(
            model_name="branch",
            name="bill_prefix",
            field=models.CharField(
                default="BILL", help_text="Prefix for bill numbers", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="gstin",
            field=models.CharField(
                blank=True,
                help_text="Branch GSTIN if different from company",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="hsn_sac_code",
            field=models.CharField(
                default="996791", help_text="HSN/SAC Code for billing", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="invoice_prefix",
            field=models.CharField(
                default="INV", help_text="Prefix for invoice numbers", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="lr_prefix",
            field=models.CharField(
                default="LR",
                help_text="Prefix for LR numbers (e.g., LR, KAL)",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="party",
            name="delivery_address",
            field=models.TextField(
                blank=True, help_text="Specific delivery address if different"
            ),
        ),
        migrations.AddField(
            model_name="truck",
            name="driver_license_no",
            field=models.CharField(
                blank=True,
                help_text="Default driver license (can be overridden in LR)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="truck",
            name="owner_pan",
            field=models.CharField(
                blank=True, help_text="Owner PAN if available", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="branch",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="party",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="truck",
            name="driver_name",
            field=models.CharField(
                blank=True,
                help_text="Default driver name (can be overridden in LR)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="truck",
            name="driver_phone",
            field=models.CharField(
                blank=True,
                help_text="Default driver phone (can be overridden in LR)",
                max_length=15,
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["code", "is_active"], name="branches_code_15cfd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["company", "is_active"], name="branches_company_582518_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="party",
            index=models.Index(
                fields=["code", "is_active"], name="parties_code_26b5be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="truck",
            index=models.Index(
                fields=["truck_number", "is_active"], name="trucks_truck_n_00a562_idx"
            ),
        ),
        migrations.AddField(
            model_name="consignor",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consignor",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consignor",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="consignor",
            index=models.Index(fields=["gstin"], name="consignors_gstin_380d2a_idx"),
        ),
        migrations.AddIndex(
            model_name="consignor",
            index=models.Index(
                fields=["code", "is_active"], name="consignors_code_a9d188_idx"
            ),
        ),
    ]
