# Generated by Django 5.2.10 on 2026-01-08 05:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lr', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HirePaymentAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpa_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('hpa_date', models.DateField(default=django.utils.timezone.now)),
                ('freight_amount', models.DecimalField(decimal_places=2, help_text='Total freight (from LR)', max_digits=10)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0, help_text='Advance payment given', max_digits=10)),
                ('diesel_amount', models.DecimalField(decimal_places=2, default=0, help_text='Diesel cost', max_digits=10)),
                ('loading_charges', models.DecimalField(decimal_places=2, default=0, help_text='Loading charges', max_digits=10)),
                ('unloading_charges', models.DecimalField(decimal_places=2, default=0, help_text='Unloading charges', max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, help_text='Other deductions', max_digits=10)),
                ('other_deductions_description', models.TextField(blank=True, help_text='Description of other deductions', null=True)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Sum of all deductions', max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Balance to be paid (freight - deductions)', max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount actually paid', max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI')], max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hpas_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hpas_deleted', to=settings.AUTH_USER_MODEL)),
                ('lr', models.ForeignKey(help_text='Linked Lorry Receipt', on_delete=django.db.models.deletion.PROTECT, related_name='hpas', to='lr.lorryreceipt')),
                ('truck', models.ForeignKey(help_text='Truck (auto-populated from LR)', on_delete=django.db.models.deletion.PROTECT, related_name='hpas', to='masters.truck')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hpas_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hire Payment Advice',
                'verbose_name_plural': 'Hire Payment Advices',
                'db_table': 'hire_payment_advices',
                'ordering': ['-created_at'],
            },
        ),
    ]
