# Generated by Django 4.2.7 on 2026-01-09 10:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lr", "0001_initial"),
        ("masters", "0002_consignor_alter_party_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HirePaymentAdvice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "hpa_number",
                    models.CharField(
                        editable=False,
                        help_text="Same as LR Number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        help_text="Invoice/Serial number (e.g., 20153572)",
                        max_length=50,
                    ),
                ),
                ("hpa_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "from_location",
                    models.CharField(
                        help_text="Loading location (from LR, can be updated)",
                        max_length=200,
                    ),
                ),
                (
                    "to_location",
                    models.CharField(
                        help_text="Unloading destination (from LR, can be updated)",
                        max_length=200,
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        blank=True,
                        help_text="Owner name (if different)",
                        max_length=200,
                    ),
                ),
                (
                    "owner_mob",
                    models.CharField(
                        blank=True,
                        help_text="Owner mobile (if different)",
                        max_length=15,
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(help_text="Driver name", max_length=200),
                ),
                (
                    "driver_mob",
                    models.CharField(
                        blank=True, default="", help_text="Driver mobile", max_length=15
                    ),
                ),
                (
                    "lr_reference",
                    models.CharField(
                        blank=True,
                        help_text="LR Number reference (for display)",
                        max_length=50,
                    ),
                ),
                (
                    "tons",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity in tons (from LR)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "rate_per_tonne",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rate per tonne",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "lorry_hire_rs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total lorry hire amount (Tons × Rate per Tonne)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "advance_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Advance amount already paid",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "diesel_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Diesel cost",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "pump_name",
                    models.CharField(
                        blank=True, help_text="Diesel pump name", max_length=200
                    ),
                ),
                (
                    "bank_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Bank deduction/amount",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "other_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Any other deductions",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "other_deductions_description",
                    models.TextField(
                        blank=True, help_text="Description of other deductions"
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Total deductions (advance + diesel + bank + others)",
                        max_digits=12,
                    ),
                ),
                (
                    "balance_rs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Balance amount to be paid (Lorry Hire - Total Deductions)",
                        max_digits=12,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Payment"),
                            ("PARTIAL", "Partially Paid"),
                            ("PAID", "Fully Paid"),
                        ],
                        default="PENDING",
                        help_text="Payment status after delivery",
                        max_length=20,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount actually paid to driver",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, help_text="Date when balance was paid", null=True
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("UPI", "UPI"),
                            ("BANK", "Bank"),
                        ],
                        help_text="Mode of payment (Cash/Cheque/Bank Transfer/UPI)",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="I have received above quantity in good condition & I am responsible for good delivery to the party\nminimum 3 Delivery",
                        help_text="Note on HPA form",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Branch creating this HPA",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hire_payment_advices",
                        to="masters.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lr",
                    models.OneToOneField(
                        help_text="Linked Lorry Receipt (HPA number matches LR number)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hpa",
                        to="lr.lorryreceipt",
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        help_text="Truck (auto-populated from LR, can be updated)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hire_payment_advices",
                        to="masters.truck",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hire Payment Advice (HPA)",
                "verbose_name_plural": "Hire Payment Advices (HPA)",
                "db_table": "hire_payment_advices",
                "ordering": ["-hpa_date", "-hpa_number"],
                "indexes": [
                    models.Index(
                        fields=["hpa_number"], name="hire_paymen_hpa_num_1e5888_idx"
                    ),
                    models.Index(
                        fields=["branch", "hpa_date"],
                        name="hire_paymen_branch__171747_idx",
                    ),
                    models.Index(
                        fields=["lr", "payment_status"],
                        name="hire_paymen_lr_id_2dc79c_idx",
                    ),
                    models.Index(
                        fields=["truck", "payment_status"],
                        name="hire_paymen_truck_i_21cff9_idx",
                    ),
                    models.Index(
                        fields=["payment_status"], name="hire_paymen_payment_705d52_idx"
                    ),
                ],
            },
        ),
    ]
