# Generated by Django 4.2.7 on 2026-01-10 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hpa", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hirepaymentadvice",
            name="advance_paid",
        ),
        migrations.AddField(
            model_name="hirepaymentadvice",
            name="advance_paid_rs",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Less Advance amount (deducted from lorry hire)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
