# Generated by Django 4.2.7 on 2026-01-10 06:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("masters", "0002_consignor_alter_party_options_and_more"),
        ("hpa", "0002_remove_hirepaymentadvice_advance_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING_BILL", "Pending Bill Creation"),
                    ("PENDING", "Pending Payment"),
                    ("PARTIAL", "Partially Paid"),
                    ("PAID", "Fully Paid"),
                ],
                default="PENDING",
                help_text="Payment status after delivery",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="HPATransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated transaction number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "transaction_date",
                    models.DateField(
                        default=django.utils.timezone.now, help_text="Transaction date"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("ADVANCE", "Advance Payment"),
                            ("DIESEL", "Diesel"),
                            ("BANK", "Bank Deduction"),
                            ("EXTRA", "Extra Charge"),
                            ("OTHER", "Other Deduction"),
                        ],
                        help_text="Type of transaction",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("UPI", "UPI"),
                            ("NEFT", "NEFT"),
                            ("RTGS", "RTGS"),
                            ("IMPS", "IMPS"),
                        ],
                        help_text="Payment mode (for advance payments)",
                        max_length=20,
                    ),
                ),
                (
                    "pump_name",
                    models.CharField(
                        blank=True,
                        help_text="Diesel pump name (for DIESEL type)",
                        max_length=200,
                    ),
                ),
                (
                    "cheque_number",
                    models.CharField(
                        blank=True,
                        help_text="Cheque number (if payment mode is Cheque)",
                        max_length=50,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, help_text="Bank name", max_length=200),
                ),
                (
                    "upi_transaction_id",
                    models.CharField(
                        blank=True, help_text="UPI Transaction ID", max_length=100
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Reference/Transaction number",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the transaction"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Additional remarks/notes"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Transaction proof/document attachment",
                        null=True,
                        upload_to="hpa_transactions/",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Branch processing this transaction",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hpa_transactions",
                        to="masters.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hpa",
                    models.ForeignKey(
                        help_text="HPA this transaction is against",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="hpa.hirepaymentadvice",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "HPA Transaction",
                "verbose_name_plural": "HPA Transactions",
                "db_table": "hpa_transactions",
                "ordering": ["-transaction_date", "-transaction_number"],
                "indexes": [
                    models.Index(
                        fields=["hpa", "transaction_date"],
                        name="hpa_transac_hpa_id_632af6_idx",
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="hpa_transac_transac_d53320_idx",
                    ),
                    models.Index(
                        fields=["transaction_date"],
                        name="hpa_transac_transac_5f6253_idx",
                    ),
                    models.Index(
                        fields=["branch", "transaction_date"],
                        name="hpa_transac_branch__90de7a_idx",
                    ),
                ],
            },
        ),
    ]
