# Generated by Django 4.2.7 on 2026-01-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hpa", "0003_alter_hirepaymentadvice_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hpatransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("ADVANCE", "Advance Payment"),
                    ("DIESEL", "Diesel"),
                    ("BANK", "Bank Deduction"),
                    ("EXTRA", "Extra Charge"),
                    ("OTHER", "Other Deduction"),
                    ("BALANCE_PAYMENT", "Balance Payment"),
                ],
                help_text="Type of transaction",
                max_length=20,
            ),
        ),
    ]
