# Generated by Django 4.2.7 on 2026-01-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hpa", "0005_change_lr_to_foreignkey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="hpa_number",
            field=models.CharField(
                editable=False,
                help_text="HPA Number (uses first LR number or generated)",
                max_length=20,
                unique=True,
            ),
        ),
    ]
