# Generated by Django 4.2.7 on 2026-01-31 07:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hpa", "0006_alter_hirepaymentadvice_hpa_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="HPAInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Invoice/Serial number (e.g., 20153572)",
                        max_length=50,
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(blank=True, help_text="Invoice date", null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Invoice amount",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True, help_text="Remarks for this invoice", max_length=255
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hpa",
                    models.ForeignKey(
                        help_text="Parent HPA",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="hpa.hirepaymentadvice",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "HPA Invoice",
                "verbose_name_plural": "HPA Invoices",
                "db_table": "hpa_invoices",
                "ordering": ["-invoice_date", "invoice_number"],
                "indexes": [
                    models.Index(
                        fields=["invoice_number"], name="hpa_invoice_invoice_91b4b9_idx"
                    ),
                    models.Index(
                        fields=["hpa", "invoice_number"],
                        name="hpa_invoice_hpa_id_cb5c2a_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="hpainvoice",
            constraint=models.UniqueConstraint(
                fields=("hpa", "invoice_number"), name="unique_hpa_invoice_number"
            ),
        ),
    ]
