# Generated by Django 4.2.7 on 2026-01-31 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lr",
            "0006_rename_lr_items_lr_id_sequence_idx_lr_items_lr_id_4b2b1a_idx_and_more",
        ),
        ("hpa", "0007_add_hpa_invoice_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hpainvoice",
            options={
                "ordering": [
                    "hpa",
                    "sequence_number",
                    "-invoice_date",
                    "invoice_number",
                ],
                "verbose_name": "HPA Invoice",
                "verbose_name_plural": "HPA Invoices",
            },
        ),
        migrations.AddField(
            model_name="hpainvoice",
            name="destination",
            field=models.CharField(
                blank=True,
                help_text="Final destination for this invoice (if different from to_location)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="hpainvoice",
            name="from_location",
            field=models.CharField(
                blank=True, help_text="Pickup location for this invoice", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="hpainvoice",
            name="lrs",
            field=models.ManyToManyField(
                blank=True,
                help_text="LRs associated with this invoice (multiple LRs can be linked to one invoice)",
                related_name="hpa_invoices",
                to="lr.lorryreceipt",
            ),
        ),
        migrations.AddField(
            model_name="hpainvoice",
            name="material_description",
            field=models.TextField(
                blank=True, help_text="Material description for this invoice"
            ),
        ),
        migrations.AddField(
            model_name="hpainvoice",
            name="number_of_bags",
            field=models.IntegerField(
                default=0,
                help_text="Number of bags for this invoice",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="hpainvoice",
            name="quantity_mt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Quantity in Metric Tons for this invoice",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="hpainvoice",
            name="sequence_number",
            field=models.IntegerField(
                default=1, help_text="Order sequence within HPA for display"
            ),
        ),
        migrations.AddField(
            model_name="hpainvoice",
            name="to_location",
            field=models.CharField(
                blank=True,
                help_text="Delivery destination for this invoice",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="hpainvoice",
            name="invoice_number",
            field=models.CharField(
                help_text="Invoice/Serial number (e.g., 20153572, INV-001)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="hpainvoice",
            name="remarks",
            field=models.TextField(blank=True, help_text="Invoice-specific remarks"),
        ),
        migrations.AddIndex(
            model_name="hpainvoice",
            index=models.Index(
                fields=["hpa", "sequence_number"], name="hpa_invoice_hpa_id_4b7e9d_idx"
            ),
        ),
    ]
