# Generated by Django 4.2.7 on 2026-02-01 05:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "lr",
            "0006_rename_lr_items_lr_id_sequence_idx_lr_items_lr_id_4b2b1a_idx_and_more",
        ),
        ("masters", "0003_auditlog"),
        ("hpa", "0008_add_invoice_lr_location_tracking"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hpainvoice",
            options={
                "ordering": ["hpa", "sequence_number", "id"],
                "verbose_name": "HPA Invoice",
                "verbose_name_plural": "HPA Invoices",
            },
        ),
        migrations.RemoveConstraint(
            model_name="hpainvoice",
            name="unique_hpa_invoice_number",
        ),
        migrations.RemoveIndex(
            model_name="hpainvoice",
            name="hpa_invoice_hpa_id_cb5c2a_idx",
        ),
        migrations.RemoveField(
            model_name="hirepaymentadvice",
            name="advance_paid_rs",
        ),
        migrations.AddField(
            model_name="hirepaymentadvice",
            name="less_advance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Less Advance paid",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="additional_lrs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional Lorry Receipts",
                related_name="additional_hpas",
                to="lr.lorryreceipt",
            ),
        ),
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="balance_rs",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Balance amount to be paid",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="bank_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Bank transfer amount",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="diesel_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Diesel payment",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="from_location",
            field=models.CharField(
                help_text="Loading location (e.g., Chettinad Dachepalli)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="hpa_number",
            field=models.CharField(
                editable=False,
                help_text="HPA Number (e.g., 10003)",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="lr",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary Lorry Receipt",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_hpas",
                to="lr.lorryreceipt",
            ),
        ),
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="lr_reference",
            field=models.CharField(
                blank=True, help_text="LR Number reference", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="other_deductions_description",
            field=models.TextField(
                blank=True, help_text="Description of other deductions/charges"
            ),
        ),
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="owner_mob",
            field=models.CharField(blank=True, help_text="Owner mobile", max_length=15),
        ),
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="owner_name",
            field=models.CharField(blank=True, help_text="Owner name", max_length=200),
        ),
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount actually paid",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="payment_date",
            field=models.DateField(
                blank=True, help_text="Date when payment was made", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="payment_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASH", "Cash"),
                    ("CHEQUE", "Cheque"),
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("UPI", "UPI"),
                    ("BANK", "Bank"),
                ],
                help_text="Mode of payment",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Payment"),
                    ("PENDING_BILL", "Pending Bill"),
                    ("PARTIAL", "Partially Paid"),
                    ("PAID", "Fully Paid"),
                ],
                default="PENDING",
                help_text="Payment status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="to_location",
            field=models.CharField(
                help_text="Unloading destination (e.g., Proddatur)", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="tons",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Quantity in tons",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="total_deductions",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Total deductions",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="hirepaymentadvice",
            name="truck",
            field=models.ForeignKey(
                help_text="Truck",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hire_payment_advices",
                to="masters.truck",
            ),
        ),
        migrations.AlterField(
            model_name="hpainvoice",
            name="invoice_date",
            field=models.DateField(
                blank=True,
                help_text="Invoice date if different from HPA date",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpainvoice",
            name="invoice_number",
            field=models.CharField(
                help_text="Invoice/Serial number (e.g., 20153572)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="hpainvoice",
            name="lrs",
            field=models.ManyToManyField(
                help_text="LRs associated with this invoice",
                related_name="hpa_invoices",
                to="lr.lorryreceipt",
            ),
        ),
        migrations.AlterField(
            model_name="hpainvoice",
            name="sequence_number",
            field=models.IntegerField(default=1, help_text="Order sequence within HPA"),
        ),
        migrations.AlterUniqueTogether(
            name="hpainvoice",
            unique_together={("hpa", "invoice_number")},
        ),
        migrations.RemoveField(
            model_name="hpainvoice",
            name="amount",
        ),
    ]
