# Generated by Django 4.2.7 on 2026-02-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hpa", "0009_alter_hpainvoice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hirepaymentadvice",
            name="bank_name",
            field=models.CharField(
                blank=True, help_text="Bank name for transfer", max_length=200
            ),
        ),
    ]
