# Generated by Django 4.2.7 on 2026-01-09 12:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("masters", "0002_consignor_alter_party_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "date",
                    models.DateField(db_index=True, help_text="Date for daily stats"),
                ),
                (
                    "total_lrs",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "pending_lrs",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "in_transit_lrs",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "delivered_lrs",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cancelled_lrs",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_hpas",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "pending_hpas",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "partial_hpas",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "paid_hpas",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_pods",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "pending_pods",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "delivered_pods",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_bills",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "pending_bills",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "paid_bills",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total revenue for the period",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "pending_payments",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total pending payments",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_freight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total freight amount",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "active_trucks",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_trucks",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_consignors",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_parties",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "stats_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily Stats"),
                            ("WEEKLY", "Weekly Stats"),
                            ("MONTHLY", "Monthly Stats"),
                            ("YTD", "Year to Date"),
                            ("ALL_TIME", "All Time"),
                        ],
                        db_index=True,
                        default="DAILY",
                        max_length=20,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Branch these stats belong to (null for all-branches aggregate)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_stats",
                        to="masters.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered stats creation (usually system)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dashboard_stats_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated stats (usually system)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dashboard_stats_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Statistics",
                "verbose_name_plural": "Dashboard Statistics",
                "db_table": "dashboard_stats",
                "ordering": ["-date", "-last_updated"],
                "indexes": [
                    models.Index(
                        fields=["branch", "date", "stats_type"],
                        name="dashboard_s_branch__a337ca_idx",
                    ),
                    models.Index(
                        fields=["branch", "stats_type", "-date"],
                        name="dashboard_s_branch__79f102_idx",
                    ),
                    models.Index(
                        fields=["-last_updated"], name="dashboard_s_last_up_fd012f_idx"
                    ),
                    models.Index(
                        fields=["date", "stats_type"],
                        name="dashboard_s_date_69afb2_idx",
                    ),
                ],
                "unique_together": {("branch", "date", "stats_type")},
            },
        ),
    ]
