# Generated by Django 4.2.7 on 2026-02-01 05:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("masters", "0003_auditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hpa", "0009_alter_hpainvoice_options_and_more"),
        (
            "lr",
            "0006_rename_lr_items_lr_id_sequence_idx_lr_items_lr_id_4b2b1a_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("ADVANCE", "Advance Payment"),
                            ("DIESEL", "Diesel Payment"),
                            ("BANK", "Bank Transfer"),
                            ("BALANCE", "Balance Payment"),
                            ("DEDUCTION", "Deduction"),
                            ("TOLL", "Toll Payment"),
                            ("COMMISSION", "Commission"),
                            ("OTHER", "Other Charges"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("UPI", "UPI"),
                            ("RTGS", "RTGS/NEFT"),
                            ("FUEL_CARD", "Fuel Card"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Transaction/Cheque/Reference number",
                        max_length=100,
                    ),
                ),
                (
                    "pump_name",
                    models.CharField(
                        blank=True, help_text="Diesel pump name", max_length=100
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("remarks", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="payment_attachments/"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch this payment belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to="masters.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hpa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to="hpa.hirepaymentadvice",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_transactions",
                "ordering": ["-payment_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["hpa", "payment_type"],
                        name="payment_tra_hpa_id_6fbd54_idx",
                    ),
                    models.Index(
                        fields=["payment_date"], name="payment_tra_payment_4be022_idx"
                    ),
                    models.Index(
                        fields=["branch", "payment_date"],
                        name="payment_tra_branch__57df7c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HPALRLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tonnage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tonnage for this LR in this HPA",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "rate_per_tonne",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rate per tonne for this LR",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount for this LR (tonnage × rate)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "special_rate_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for special rate if different from standard",
                        max_length=200,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch this link belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hpa_lr_links",
                        to="masters.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hpa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lr_links",
                        to="hpa.hirepaymentadvice",
                    ),
                ),
                (
                    "lr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hpa_links",
                        to="lr.lorryreceipt",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hpa_lr_links",
                "ordering": ["hpa", "lr__lr_number"],
                "indexes": [
                    models.Index(fields=["hpa"], name="hpa_lr_link_hpa_id_ca55da_idx"),
                    models.Index(fields=["lr"], name="hpa_lr_link_lr_id_917d75_idx"),
                    models.Index(
                        fields=["branch"], name="hpa_lr_link_branch__8e5334_idx"
                    ),
                ],
                "unique_together": {("hpa", "lr")},
            },
        ),
    ]
