# Generated by Django 5.2.10 on 2026-01-07 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LorryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lr_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('from_location', models.CharField(max_length=200)),
                ('to_location', models.CharField(max_length=200)),
                ('material_description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_in_tons', models.DecimalField(decimal_places=3, help_text='Weight in tons', max_digits=10)),
                ('freight_amount', models.DecimalField(decimal_places=2, help_text='Total freight amount', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('lr_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('invoice_edited_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lorry_receipts', to='masters.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('invoice_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_edits', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(help_text='Customer/Consignee', on_delete=django.db.models.deletion.PROTECT, related_name='lorry_receipts', to='masters.party')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lorry_receipts', to='masters.truck')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lorry Receipt',
                'verbose_name_plural': 'Lorry Receipts',
                'db_table': 'lorry_receipts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lr_number'], name='lorry_recei_lr_numb_d748b8_idx'), models.Index(fields=['branch', 'status'], name='lorry_recei_branch__8d7111_idx'), models.Index(fields=['party'], name='lorry_recei_party_i_f5e230_idx'), models.Index(fields=['lr_date'], name='lorry_recei_lr_date_079ed2_idx')],
            },
        ),
    ]
