# Generated by Django 4.2.7 on 2026-01-09 10:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("masters", "0002_consignor_alter_party_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LorryReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lr_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("lr_date", models.DateField(blank=True, null=True)),
                (
                    "sap_number",
                    models.CharField(
                        blank=True, help_text="SAP Number from consignor", max_length=50
                    ),
                ),
                (
                    "lr_submitted_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time when LR was submitted/issued",
                        null=True,
                    ),
                ),
                (
                    "delivery_at",
                    models.CharField(
                        blank=True,
                        help_text="Specific delivery location if different",
                        max_length=200,
                    ),
                ),
                (
                    "from_location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Loading location",
                        max_length=200,
                    ),
                ),
                (
                    "to_location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Unloading destination",
                        max_length=200,
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        blank=True, help_text="Final destination", max_length=200
                    ),
                ),
                (
                    "material_description",
                    models.TextField(blank=True, help_text="Description of goods"),
                ),
                (
                    "quantity_mt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity in Metric Tons (M.T.)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "number_of_bags",
                    models.IntegerField(
                        default=0,
                        help_text="Number of bags",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("53", "Grade 53"),
                            ("43", "Grade 43"),
                            ("OPC", "OPC (Ordinary Portland Cement)"),
                            ("PPC", "PPC (Portland Pozzolana Cement)"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Grade of material (53/43/OPC)",
                        max_length=10,
                    ),
                ),
                (
                    "grade_quantity",
                    models.CharField(
                        blank=True,
                        help_text="Grade quantity (e.g., 35MT OPC)",
                        max_length=50,
                    ),
                ),
                (
                    "loading_from_department",
                    models.CharField(
                        blank=True,
                        default="DISTRIBUTION DEPARTMENT",
                        help_text="Loading from department",
                        max_length=100,
                    ),
                ),
                ("please_load", models.CharField(blank=True, max_length=100)),
                (
                    "number_of_loads",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "grade_type_of_pkg",
                    models.CharField(
                        blank=True, help_text="Grade/Type of Package", max_length=100
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Driver name for this trip",
                        max_length=200,
                    ),
                ),
                (
                    "driver_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Driver mobile number",
                        max_length=15,
                    ),
                ),
                (
                    "driver_license_no",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Driver license number",
                        max_length=50,
                    ),
                ),
                (
                    "freight_rate_per_ton",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Freight rate per ton",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "freight_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total freight amount (Rate × Quantity)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_term",
                    models.CharField(
                        choices=[
                            ("TO_BE_BILLED", "To Be Billed"),
                            ("TO_PAY", "To Pay"),
                            ("PAID", "Paid"),
                        ],
                        default="TO_BE_BILLED",
                        help_text="Terms of payment",
                        max_length=20,
                    ),
                ),
                (
                    "gst_payable_by",
                    models.CharField(
                        default="SERVICE",
                        help_text="GST payable by (Service/Consignor/Consignee)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued to Driver"),
                            ("LOADING", "At Loading Point"),
                            ("IN_TRANSIT", "In Transit"),
                            ("AT_UNLOADING", "At Unloading Point"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("expected_loading_date", models.DateField(blank=True, null=True)),
                ("actual_loading_date", models.DateField(blank=True, null=True)),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                ("actual_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Additional remarks or notes"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="नोट : १५ दिन के अंदर नहीं तो गाडी का भाडा नही मिलेगा !",
                        help_text="Note to driver (default Hindi note about 15 days)",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch creating this LR",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lorry_receipts",
                        to="masters.branch",
                    ),
                ),
                (
                    "consignee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Party receiving the goods",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lorry_receipts",
                        to="masters.party",
                    ),
                ),
                (
                    "consignor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Company sending the goods",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lorry_receipts",
                        to="masters.consignor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned truck",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lorry_receipts",
                        to="masters.truck",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lorry Receipt (LR)",
                "verbose_name_plural": "Lorry Receipts (LR)",
                "db_table": "lorry_receipts",
                "ordering": ["-lr_date", "-lr_number"],
                "indexes": [
                    models.Index(
                        fields=["lr_number"], name="lorry_recei_lr_numb_d748b8_idx"
                    ),
                    models.Index(
                        fields=["branch", "lr_date"],
                        name="lorry_recei_branch__670c2c_idx",
                    ),
                    models.Index(
                        fields=["consignor", "status"],
                        name="lorry_recei_consign_af68a0_idx",
                    ),
                    models.Index(
                        fields=["consignee", "status"],
                        name="lorry_recei_consign_814177_idx",
                    ),
                    models.Index(
                        fields=["truck", "status"],
                        name="lorry_recei_truck_i_39dbce_idx",
                    ),
                    models.Index(
                        fields=["status"], name="lorry_recei_status_bfa36f_idx"
                    ),
                ],
            },
        ),
    ]
