# Generated by Django 4.2.7 on 2026-01-10 05:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lr", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lorryreceipt",
            name="freight_amount",
        ),
        migrations.RemoveField(
            model_name="lorryreceipt",
            name="freight_rate_per_ton",
        ),
    ]
