# Generated by Django 4.2.7 on 2026-01-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lr", "0002_remove_lorryreceipt_freight_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lorryreceipt",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_HPA", "Pending HPA Creation"),
                    ("ISSUED", "Issued to Driver"),
                    ("LOADING", "At Loading Point"),
                    ("IN_TRANSIT", "In Transit"),
                    ("AT_UNLOADING", "At Unloading Point"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
