# Generated by Django 4.2.7 on 2026-01-26 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lr", "0005_migrate_existing_lr_data"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="lritem",
            new_name="lr_items_lr_id_4b2b1a_idx",
            old_name="lr_items_lr_id_sequence_idx",
        ),
        migrations.RenameIndex(
            model_name="lritem",
            new_name="lr_items_consign_d49ea1_idx",
            old_name="lr_items_consignor_idx",
        ),
        migrations.RenameIndex(
            model_name="lritem",
            new_name="lr_items_consign_a15fd6_idx",
            old_name="lr_items_consignee_idx",
        ),
    ]
