# Generated by Django 4.2.7 on 2026-01-09 10:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lr", "0001_initial"),
        ("masters", "0002_consignor_alter_party_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bill_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "bill_date",
                    models.DateField(blank=True, help_text="Bill date", null=True),
                ),
                (
                    "from_date",
                    models.DateField(
                        blank=True,
                        help_text="From date (start of billing period)",
                        null=True,
                    ),
                ),
                (
                    "to_date",
                    models.DateField(
                        blank=True,
                        help_text="To date (end of billing period)",
                        null=True,
                    ),
                ),
                (
                    "hsn_sac_code",
                    models.CharField(
                        default="996791",
                        help_text="HSN/SAC Code for service",
                        max_length=20,
                    ),
                ),
                (
                    "vendor_code",
                    models.CharField(
                        blank=True, help_text="Vendor/Transporter Code", max_length=50
                    ),
                ),
                (
                    "gstin",
                    models.CharField(
                        blank=True, help_text="Bill issuer GSTIN", max_length=15
                    ),
                ),
                (
                    "consignor_gstin",
                    models.CharField(
                        blank=True, help_text="Consignor GSTIN", max_length=15
                    ),
                ),
                (
                    "consignor_pan",
                    models.CharField(
                        blank=True, help_text="Consignor PAN", max_length=10
                    ),
                ),
                (
                    "state_code",
                    models.CharField(
                        blank=True, help_text="State code for GST", max_length=2
                    ),
                ),
                (
                    "gst_payable_by",
                    models.CharField(
                        default="SERVICE",
                        help_text="GST payable by (Service/Consignor/Consignee)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("GENERATED", "Generated"),
                            ("SENT", "Sent to Consignor"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        help_text="Bill status",
                        max_length=20,
                    ),
                ),
                (
                    "total_quantity_mt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Total quantity in MT",
                        max_digits=12,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Total amount before GST (sum of all line items)",
                        max_digits=12,
                    ),
                ),
                (
                    "sgst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=9.0,
                        help_text="SGST rate (percentage)",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cgst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=9.0,
                        help_text="CGST rate (percentage)",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="SGST amount",
                        max_digits=12,
                    ),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="CGST amount",
                        max_digits=12,
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Grand total (Total + SGST + CGST)",
                        max_digits=12,
                    ),
                ),
                (
                    "payment_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount received",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(blank=True, help_text="Payment date", null=True),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        blank=True,
                        help_text="Payment mode (Cash/Cheque/Bank Transfer)",
                        max_length=50,
                    ),
                ),
                ("remarks", models.TextField(blank=True, help_text="Internal remarks")),
                (
                    "consignor_note",
                    models.TextField(blank=True, help_text="Note for consignor"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Branch creating this bill",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="masters.branch",
                    ),
                ),
                (
                    "consignor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Company receiving this bill (consignor)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="masters.consignor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill/Invoice",
                "verbose_name_plural": "Bills/Invoices",
                "db_table": "bills",
                "ordering": ["-bill_date", "-bill_number"],
            },
        ),
        migrations.CreateModel(
            name="BillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "destination",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Delivery destination",
                        max_length=200,
                    ),
                ),
                (
                    "quantity_mt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity in MT",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "freight_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Freight rate per ton",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount (Quantity × Freight Rate)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True, help_text="Line item remarks", max_length=500
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        help_text="Parent bill",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_items",
                        to="billing.bill",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lr",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked Lorry Receipt",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bill_items",
                        to="lr.lorryreceipt",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill Item",
                "verbose_name_plural": "Bill Items",
                "db_table": "bill_items",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["bill", "id"], name="bill_items_bill_id_daed8c_idx"
                    ),
                    models.Index(fields=["lr"], name="bill_items_lr_id_75c6b0_idx"),
                ],
                "unique_together": {("bill", "lr")},
            },
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["bill_number"], name="bills_bill_nu_ba9272_idx"),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["branch", "bill_date"], name="bills_branch__183692_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["consignor", "status"], name="bills_consign_6a0f86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["status"], name="bills_status_d22f38_idx"),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["from_date", "to_date"], name="bills_from_da_dffa47_idx"
            ),
        ),
    ]
