# Generated by Django 4.2.7 on 2026-01-26 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_update_bill_item_to_lr_item"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="billitem",
            new_name="bill_items_lr_item_769a0b_idx",
            old_name="bill_items_lr_item_idx",
        ),
    ]
