# Generated by Django 4.2.7 on 2026-01-31 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("masters", "0003_auditlog"),
        ("billing", "0003_rename_bill_items_lr_item_idx_bill_items_lr_item_769a0b_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Template name (e.g., "Chettinad Detailed Format")',
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text='Unique template code (e.g., "CHET_DET_V1")',
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Template description and purpose"
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard Format"),
                            ("DETAILED", "Detailed with Breakdown"),
                            ("SUMMARY", "Summary Format"),
                            ("CUSTOM", "Custom Format"),
                        ],
                        default="STANDARD",
                        help_text="Template category",
                        max_length=20,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Default template for this consignor (or global default if no consignor)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether template is available for use"
                    ),
                ),
                (
                    "field_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        Field visibility configuration:\n        {\n            "show_lr_number": true,\n            "show_invoice_number": true,\n            "show_truck_number": true,\n            "show_driver_name": false,\n            "show_hpa_number": true,\n            "show_freight_breakdown": true,\n            "show_loading_charges": false,\n            "show_unloading_charges": false,\n            "show_material_description": true,\n            "show_destination": true,\n            "show_consignee": true\n        }\n        ',
                    ),
                ),
                (
                    "calculation_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        Calculation formulas and rules:\n        {\n            "freight_formula": "quantity_mt * rate_per_mt",\n            "loading_charges_type": "fixed",\n            "loading_charges_value": 100,\n            "unloading_charges_type": "per_mt",\n            "unloading_charges_value": 50,\n            "round_off": true,\n            "round_direction": "nearest"\n        }\n        ',
                    ),
                ),
                (
                    "grouping_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        How to group line items:\n        {\n            "group_by": "destination",\n            "sort_by": "date",\n            "sort_order": "asc",\n            "show_subtotals": true,\n            "merge_same_destination": false\n        }\n        ',
                    ),
                ),
                (
                    "tax_configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        GST and tax settings:\n        {\n            "gst_applicable": true,\n            "gst_type": "intra_state",\n            "sgst_rate": 9.0,\n            "cgst_rate": 9.0,\n            "igst_rate": 18.0,\n            "tds_applicable": false,\n            "tds_rate": 2.0,\n            "hsn_sac_code": "996791"\n        }\n        ',
                    ),
                ),
                (
                    "display_options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        UI display preferences:\n        {\n            "date_format": "DD/MM/YYYY",\n            "number_format": "indian",\n            "currency_symbol": "Rs.",\n            "decimal_places": 2,\n            "show_amount_in_words": true,\n            "header_text": "Tax Invoice",\n            "footer_text": "Terms and conditions apply"\n        }\n        ',
                    ),
                ),
                (
                    "pdf_template_name",
                    models.CharField(
                        default="default_bill",
                        help_text="PDF template file name (without extension)",
                        max_length=100,
                    ),
                ),
                (
                    "header_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        PDF header configuration:\n        {\n            "show_logo": true,\n            "logo_position": "left",\n            "company_name_size": 18,\n            "address_size": 10,\n            "show_gstin_header": true\n        }\n        ',
                    ),
                ),
                (
                    "footer_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        PDF footer configuration:\n        {\n            "show_bank_details": true,\n            "show_terms": true,\n            "show_signature_line": true,\n            "terms_text": "Payment due within 30 days"\n        }\n        ',
                    ),
                ),
                (
                    "page_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        PDF page settings:\n        {\n            "paper_size": "A4",\n            "orientation": "portrait",\n            "margin_top": 20,\n            "margin_bottom": 20,\n            "margin_left": 15,\n            "margin_right": 15\n        }\n        ',
                    ),
                ),
                (
                    "consignor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific consignor (null = global template)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_templates",
                        to="masters.consignor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Template",
                "verbose_name_plural": "Billing Templates",
                "db_table": "billing_templates",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="bill",
            name="billing_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Billing template used for this bill (determines format and calculations)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bills",
                to="billing.billingtemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="billingtemplate",
            index=models.Index(fields=["code"], name="billing_tem_code_d43d92_idx"),
        ),
        migrations.AddIndex(
            model_name="billingtemplate",
            index=models.Index(
                fields=["consignor", "is_default"],
                name="billing_tem_consign_a59465_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="billingtemplate",
            index=models.Index(
                fields=["template_type", "is_active"],
                name="billing_tem_templat_a76deb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("consignor", "is_default"),
                name="unique_default_template_per_consignor",
            ),
        ),
    ]
