# Generated by Django 4.2.7 on 2026-01-31 08:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0004_add_billing_template_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="due_date",
            field=models.DateField(blank=True, help_text="Payment due date", null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PARTIAL", "Partially Paid"),
                    ("PAID", "Fully Paid"),
                    ("OVERDUE", "Overdue"),
                ],
                default="PENDING",
                help_text="Payment collection status",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ClientPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_date",
                    models.DateField(help_text="Date payment was received"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("UPI", "UPI"),
                            ("RTGS", "RTGS"),
                            ("NEFT", "NEFT"),
                            ("DD", "Demand Draft"),
                            ("OTHER", "Other"),
                        ],
                        default="BANK_TRANSFER",
                        help_text="Method of payment",
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Cheque number, transaction ID, or reference",
                        max_length=100,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        help_text="Bank name (for cheque/DD)",
                        max_length=100,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Payment remarks or notes"),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        help_text="Bill against which payment is made",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_payments",
                        to="billing.bill",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Payment",
                "verbose_name_plural": "Client Payments",
                "db_table": "client_payments",
                "ordering": ["-payment_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["bill", "payment_date"],
                        name="client_paym_bill_id_dbb97e_idx",
                    ),
                    models.Index(
                        fields=["payment_date"], name="client_paym_payment_15cc52_idx"
                    ),
                    models.Index(
                        fields=["payment_method"], name="client_paym_payment_4707f7_idx"
                    ),
                ],
            },
        ),
    ]
