# Generated by Django 4.2.7 on 2026-01-31 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hpa", "0008_add_invoice_lr_location_tracking"),
        ("billing", "0005_add_payment_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="billitem",
            name="hpa_invoice",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked HPA Invoice (to track which invoices have been billed)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bill_items",
                to="hpa.hpainvoice",
            ),
        ),
    ]
