# Generated by Django 4.2.7 on 2026-01-09 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("masters", "0002_consignor_alter_party_options_and_more"),
        ("accounts", "0002_add_branch_and_update_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch assignment (null for admin/auditor roles)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="masters.branch",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role", "branch"], name="users_role_e0e59d_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "is_active_branch"],
                name="users_is_acti_e368ea_idx",
            ),
        ),
    ]
