# Generated by Django 4.2.7 on 2026-01-09 10:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lr", "0001_initial"),
        ("hpa", "0001_initial"),
        ("masters", "0002_consignor_alter_party_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProofOfDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pod_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "pod_date",
                    models.DateField(
                        blank=True, help_text="Date when POD was received", null=True
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True, help_text="Actual delivery date", null=True
                    ),
                ),
                (
                    "delivery_time",
                    models.TimeField(
                        blank=True, help_text="Delivery time if available", null=True
                    ),
                ),
                (
                    "delivered_to",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of person who received delivery",
                        max_length=200,
                    ),
                ),
                (
                    "delivered_to_phone",
                    models.CharField(
                        blank=True, help_text="Phone number of receiver", max_length=15
                    ),
                ),
                (
                    "delivery_signature",
                    models.CharField(
                        blank=True, help_text="Signature of receiver", max_length=200
                    ),
                ),
                (
                    "quantity_received_mt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quantity received in MT (for verification)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "number_of_bags_received",
                    models.IntegerField(
                        default=0,
                        help_text="Number of bags received (for verification)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "goods_condition",
                    models.CharField(
                        choices=[
                            ("GOOD", "Good Condition"),
                            ("DAMAGED", "Damaged"),
                            ("SHORT", "Short Delivery"),
                            ("EXCESS", "Excess Delivery"),
                        ],
                        default="GOOD",
                        help_text="Condition of goods received",
                        max_length=50,
                    ),
                ),
                (
                    "delivery_remarks",
                    models.TextField(blank=True, help_text="Remarks about delivery"),
                ),
                (
                    "consignee_remarks",
                    models.TextField(
                        blank=True, help_text="Remarks from consignee/receiver"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "POD Received"),
                            ("VERIFIED", "Verified"),
                            ("DISPUTED", "Disputed"),
                            ("ACCEPTED", "Accepted"),
                        ],
                        default="RECEIVED",
                        help_text="POD verification status",
                        max_length=20,
                    ),
                ),
                (
                    "pod_document",
                    models.FileField(
                        blank=True,
                        help_text="Upload POD document/photo if available",
                        null=True,
                        upload_to="pod_documents/",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="Verification timestamp", null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True, help_text="Internal remarks")),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Branch receiving this POD",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proof_of_deliveries",
                        to="masters.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hpa",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked Hire Payment Advice",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pod",
                        to="hpa.hirepaymentadvice",
                    ),
                ),
                (
                    "lr",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked Lorry Receipt",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pod",
                        to="lr.lorryreceipt",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who verified this POD",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_pods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Proof of Delivery (POD)",
                "verbose_name_plural": "Proof of Deliveries (POD)",
                "db_table": "proof_of_deliveries",
                "ordering": ["-pod_date", "-pod_number"],
                "indexes": [
                    models.Index(
                        fields=["pod_number"], name="proof_of_de_pod_num_37bee0_idx"
                    ),
                    models.Index(
                        fields=["branch", "pod_date"],
                        name="proof_of_de_branch__bb4959_idx",
                    ),
                    models.Index(
                        fields=["lr", "status"], name="proof_of_de_lr_id_d8431a_idx"
                    ),
                    models.Index(
                        fields=["hpa", "status"], name="proof_of_de_hpa_id_3798b9_idx"
                    ),
                    models.Index(
                        fields=["status"], name="proof_of_de_status_d18cac_idx"
                    ),
                ],
            },
        ),
    ]
