# Generated by Django 4.2.7 on 2026-02-01 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pod", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proofofdelivery",
            name="damage_bags",
            field=models.IntegerField(
                default=0,
                help_text="Number of damaged bags",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="damage_description",
            field=models.TextField(blank=True, help_text="Description of damage"),
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="damage_quantity_mt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Damaged quantity in MT",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="shortage_bags",
            field=models.IntegerField(
                default=0,
                help_text="Shortage in number of bags",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="shortage_quantity_mt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Shortage quantity in MT (if any)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="proofofdelivery",
            name="shortage_reason",
            field=models.TextField(blank=True, help_text="Reason for shortage"),
        ),
    ]
