# Generated by Django 4.2.7 on 2026-01-09 12:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hpa", "0001_initial"),
        ("masters", "0002_consignor_alter_party_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_number",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated payment number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        default=django.utils.timezone.now, help_text="Payment date"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                            ("UPI", "UPI"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("NEFT", "NEFT"),
                            ("RTGS", "RTGS"),
                            ("IMPS", "IMPS"),
                        ],
                        help_text="Payment method used",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CLEARED", "Cleared"),
                            ("BOUNCED", "Bounced"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        help_text="Payment status",
                        max_length=20,
                    ),
                ),
                (
                    "cheque_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Cheque number (required if payment method is Cheque)",
                        max_length=50,
                    ),
                ),
                (
                    "cheque_date",
                    models.DateField(blank=True, help_text="Cheque date", null=True),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        help_text="Bank name (for cheque/bank transfer)",
                        max_length=200,
                    ),
                ),
                (
                    "clearing_date",
                    models.DateField(
                        blank=True, help_text="Cheque clearing date", null=True
                    ),
                ),
                (
                    "upi_transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="UPI Transaction ID/Reference Number",
                        max_length=100,
                    ),
                ),
                (
                    "upi_id",
                    models.CharField(
                        blank=True,
                        help_text="UPI ID (e.g., phone@paytm, name@ybl)",
                        max_length=100,
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Transaction reference number (for bank transfers)",
                        max_length=100,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="Account number (last 4 digits)",
                        max_length=50,
                    ),
                ),
                (
                    "ifsc_code",
                    models.CharField(blank=True, help_text="IFSC code", max_length=11),
                ),
                (
                    "received_by",
                    models.CharField(
                        blank=True,
                        help_text="Person who received cash payment",
                        max_length=200,
                    ),
                ),
                (
                    "cash_receipt_number",
                    models.CharField(
                        blank=True,
                        help_text="Cash receipt number (if any)",
                        max_length=50,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Payment remarks/notes"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Payment proof/document attachment",
                        null=True,
                        upload_to="payments/",
                    ),
                ),
                (
                    "reconciled",
                    models.BooleanField(default=False, help_text="Payment reconciled"),
                ),
                (
                    "reconciled_date",
                    models.DateField(
                        blank=True, help_text="Reconciliation date", null=True
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Branch processing this payment",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="masters.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hpa",
                    models.ForeignKey(
                        help_text="HPA this payment is against",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="hpa.hirepaymentadvice",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who reconciled this payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciled_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "payments",
                "ordering": ["-payment_date", "-payment_number"],
                "indexes": [
                    models.Index(
                        fields=["hpa", "payment_date"],
                        name="payments_hpa_id_1c6a94_idx",
                    ),
                    models.Index(
                        fields=["payment_method", "status"],
                        name="payments_payment_749428_idx",
                    ),
                    models.Index(
                        fields=["payment_date", "status"],
                        name="payments_payment_c5e0b7_idx",
                    ),
                    models.Index(
                        fields=["cheque_number"], name="payments_cheque__295d12_idx"
                    ),
                    models.Index(
                        fields=["upi_transaction_id"],
                        name="payments_upi_tra_50fa01_idx",
                    ),
                    models.Index(
                        fields=["transaction_reference"],
                        name="payments_transac_4c44f7_idx",
                    ),
                    models.Index(
                        fields=["branch", "payment_date"],
                        name="payments_branch__c4c434_idx",
                    ),
                ],
            },
        ),
    ]
